### ISSUE TITLE
Fix pulp-upload import command

### ISSUE THREAD

**Issue by aweiteka** [aweiteka/raas#35]
There is an error when a pulp repository is exported. This may be due to an improperly created pulp repo.

**Comment by aweiteka** [comment]
This should fix this: https://github.com/aweiteka/raas/commit/1d4ed847bbb34f56f9613b250106f88c51ae3b2b

Need to test

**Comment by pschiffe** [comment]
Unfortunately, mentioned commit didn't fix the problem for me :-(

**Comment by aweiteka** [comment]
Ok, finally got it working. I _think_ it was a trailing comma in the json post data. https://github.com/aweiteka/raas/commit/694376d054633d372bac6dd9240df585496da3e3
